# Generated by Django 3.0.5 on 2020-05-04 16:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PostModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название поста')),
                ('discription', models.TextField(verbose_name='Описание')),
                ('date', models.DateField(default=datetime.date.today, verbose_name='Дата создания')),
                ('top', models.BooleanField(default=False, verbose_name='Главная новость')),
            ],
            options={
                'verbose_name': 'Пост',
                'verbose_name_plural': 'Посты',
            },
        ),
    ]
