# Generated by Django 3.0.5 on 2020-05-04 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='postmodel',
            name='image',
            field=models.ImageField(default=False, upload_to='poster/', verbose_name='Постер'),
        ),
    ]
