# Generated by Django 3.0.5 on 2020-05-04 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0003_auto_20200504_1654'),
    ]

    operations = [
        migrations.AddField(
            model_name='postmodel',
            name='publick',
            field=models.BooleanField(default=True, verbose_name='Опубликован'),
        ),
    ]
