# Generated by Django 3.0.5 on 2020-05-07 13:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Post', '0004_postmodel_publick'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComandModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название команды')),
                ('logo', models.ImageField(upload_to='logo/', verbose_name='Логотип команды')),
            ],
            options={
                'verbose_name': 'Команда',
                'verbose_name_plural': 'Команды',
            },
        ),
        migrations.CreateModel(
            name='CountryModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название страны')),
                ('image', models.ImageField(upload_to='flag/', verbose_name='Изображение флага')),
            ],
            options={
                'verbose_name': 'Старана',
                'verbose_name_plural': 'Страны',
            },
        ),
        migrations.AlterField(
            model_name='postmodel',
            name='top',
            field=models.BooleanField(verbose_name='Главная новость'),
        ),
        migrations.CreateModel(
            name='TournamentModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Название турнира')),
                ('discription', models.TextField(verbose_name='Описанаие турнира')),
                ('date', models.DateField(verbose_name='Дата начала турнира')),
                ('logo', models.ImageField(upload_to='logo_tournament/', verbose_name='Логотип турнира')),
                ('prize_fond', models.SmallIntegerField(verbose_name='Призовой фонд')),
                ('active', models.BooleanField(default=False, verbose_name='Идёт в данный момент')),
                ('comand', models.ManyToManyField(related_name='comand_tournament', to='Post.ComandModel', verbose_name='Команды участники турнира')),
            ],
            options={
                'verbose_name': 'Турнир',
                'verbose_name_plural': 'турниры',
            },
        ),
        migrations.CreateModel(
            name='Reiting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place_in_the_top', models.SmallIntegerField(verbose_name='Место в топе')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Дата рейтинга')),
                ('form', models.SmallIntegerField(verbose_name='Форма команды')),
                ('victory', models.PositiveSmallIntegerField(verbose_name='колличество побед')),
                ('percent_victori', models.PositiveSmallIntegerField(verbose_name='Процент побед')),
                ('defeat', models.PositiveSmallIntegerField(verbose_name='Колиичество проигронных игр')),
                ('comand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Post.ComandModel')),
            ],
            options={
                'verbose_name': 'Рейтинг',
                'verbose_name_plural': 'Рейтинги',
            },
        ),
        migrations.CreateModel(
            name='PlayerModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Полное имя игрока')),
                ('nickname', models.CharField(max_length=50, verbose_name='Ник игрока')),
                ('photo', models.ImageField(blank=True, upload_to='photo_player/', verbose_name='Фото игрока')),
                ('comand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Post.ComandModel')),
                ('country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Post.CountryModel', verbose_name='Команда')),
            ],
            options={
                'verbose_name': 'Игрок',
                'verbose_name_plural': 'Игроки',
            },
        ),
        migrations.CreateModel(
            name='GameModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coefficient1', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Коэффициент на первую команду')),
                ('coefficient2', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Коэффициент на вторую команду')),
                ('active', models.BooleanField(default=False, verbose_name='Идёт в данный момент')),
                ('last_game', models.BooleanField(default=False, verbose_name='Игра уже прошла')),
                ('date', models.DateTimeField(verbose_name='Время начала игры')),
                ('comand1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='one_comand', to='Post.ComandModel', verbose_name='Первая команда')),
                ('comand2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='two_comand', to='Post.ComandModel', verbose_name='Вторая команда')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Post.TournamentModel')),
            ],
            options={
                'verbose_name': 'Игра',
                'verbose_name_plural': 'Игры',
            },
        ),
        migrations.CreateModel(
            name='CommentModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=500, verbose_name='Текст комментария')),
                ('date_create', models.DateTimeField(auto_now_add=True, verbose_name='Время создание комментария')),
                ('publick', models.BooleanField(default=True, verbose_name='Виден пользователям')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Post.PostModel')),
            ],
            options={
                'verbose_name': 'Комментарий',
                'verbose_name_plural': 'Комментарии',
            },
        ),
        migrations.AddField(
            model_name='comandmodel',
            name='county',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Post.CountryModel'),
        ),
    ]
