# Generated by Django 3.0.5 on 2020-05-07 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0005_auto_20200507_1306'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Reiting',
            new_name='ReitingModel',
        ),
        migrations.RenameField(
            model_name='comandmodel',
            old_name='county',
            new_name='country',
        ),
    ]
