# Generated by Django 3.0.5 on 2020-05-07 17:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0006_auto_20200507_1313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playermodel',
            name='comand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Post.ComandModel', verbose_name='Команда'),
        ),
        migrations.AlterField(
            model_name='playermodel',
            name='country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Post.CountryModel', verbose_name='Страна'),
        ),
    ]
