# Generated by Django 3.0.5 on 2020-05-08 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0008_auto_20200507_1820'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamemodel',
            name='link',
            field=models.CharField(default=False, max_length=150, verbose_name='Сыылка на тотализатор'),
        ),
    ]
