# Generated by Django 3.0.5 on 2020-05-08 14:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0011_auto_20200508_1419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videomodel',
            name='chanel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Post.ChanelModel', verbose_name='Канал'),
        ),
    ]
