# Generated by Django 3.0.5 on 2020-05-08 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0012_auto_20200508_1420'),
    ]

    operations = [
        migrations.AddField(
            model_name='videomodel',
            name='link',
            field=models.CharField(default=False, max_length=150, verbose_name='Ссылка на видео'),
        ),
    ]
