# Generated by Django 3.0.5 on 2020-05-08 18:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0014_auto_20200508_1820'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videomodel',
            name='game',
        ),
        migrations.AlterField(
            model_name='videomodel',
            name='chanel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Post.ChanelModel', verbose_name='Канал'),
        ),
        migrations.AlterField(
            model_name='videomodel',
            name='discription',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='videomodel',
            name='tournament',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Post.TournamentModel', verbose_name='Игра'),
        ),
    ]
