# Generated by Django 3.0.5 on 2020-05-08 18:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0015_auto_20200508_1824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videomodel',
            name='tournament',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Post.TournamentModel', verbose_name='Игра'),
        ),
    ]
