# Generated by Django 3.0.5 on 2020-05-09 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0019_auto_20200509_1612'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commentmodel',
            name='name',
        ),
    ]
